---

# A docker-compose file to simplify image testing.
#
#   NOTE: This file assumes docker-compose v1.27.0 or better.
#
# Use to build and test an image using the following environment variables:
#
# - DATASET_FILENAME (default 'dummy.txt')
# - IMAGE_NAME (default 'formatter')
# - TEST_DIR (default '1')
#
# See TESTING.md

services:
  formatter:
    build: .
    image: ${IMAGE_NAME:-formatter}:latest
    environment:
    - DT_DATASET_FILENAME=${DATASET_FILENAME:-dummy.txt}
    - DT_DATASET_INPUT_PATH=/dataset/input
    - DT_DATASET_OUTPUT_PATH=/dataset/output
    - DT_DATASET_EXTRA_VARIABLES=${DATASET_EXTRA_VARIABLES}
    - DT_DATASET_OUTPUT_FORMAT=$DATASET_OUTPUT_FORMAT
    - DT_DATASET_OUTPUT_FILENAME=$DATASET_OUTPUT_FILENAME
    volumes:
    - ${PWD}/test/${TEST_TYPE:-success}/${TEST_DIR:-1}:/dataset
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
